apiVersion: skaffold/v3
kind: Config
metadata:
  name: vectordb

requires:
  - path: ./pgvector

profiles:
  - name: local
  - name: chroma
    patches:
      - op: add
        path: /requires/0
        value:
          path: ./chroma
  - name: ci
