name: 'Setup Python Environment'
description: 'Set up Python with uv and install dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10.12'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ inputs.python-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ inputs.python-version }}-

    - name: Install dependencies with uv
      shell: bash
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Add venv to PATH
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
