"""Initial schema: documents, search_interactions, qa_interactions

Revision ID: dc37733dbbf5
Revises:
Create Date: 2025-12-29 22:35:10.645782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dc37733dbbf5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("document_type", sa.String(length=200), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_documents_content_hash"),
        "documents",
        ["content_hash"],
        unique=True,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_documents_title"), "documents", ["title"], unique=False, schema="app"
    )
    op.create_table(
        "qa_interactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=True),
        sa.Column("k_results", sa.Integer(), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("feedback_text", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_qa_interactions_document_id"),
        "qa_interactions",
        ["document_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_qa_interactions_session_id"),
        "qa_interactions",
        ["session_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "search_interactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.String(), nullable=False),
        sa.Column("k_results", sa.Integer(), nullable=True),
        sa.Column("results_count", sa.Integer(), nullable=True),
        sa.Column("avg_similarity_score", sa.Float(), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_search_interactions_document_id"),
        "search_interactions",
        ["document_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_search_interactions_session_id"),
        "search_interactions",
        ["session_id"],
        unique=False,
        schema="app",
    )
    op.drop_table("rag_documents")
    op.drop_index(
        "hnsw_index",
        table_name="vectorstore_test",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        "ivfflat_index",
        table_name="vectorstore_test",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "10"},
        postgresql_using="ivfflat",
    )
    op.drop_table("vectorstore_test")
    # ### end Alembic commands ###
